#ifndef __INA_PARSER_EXPR2_TOKENS_HH__
#define __INA_PARSER_EXPR2_TOKENS_HH__

extern "C" {
/** Defines all tokens of the expression lexer (internal used). */
typedef enum {
  _INA_PARSER_EXPR_TOKEN_INTEGER,
  _INA_PARSER_EXPR_TOKEN_FLOAT,
  _INA_PARSER_EXPR_TOKEN_IDENTIFIER,
  _INA_PARSER_EXPR_TOKEN_POWER,
  _INA_PARSER_EXPR_TOKEN_MULTIPLY,
  _INA_PARSER_EXPR_TOKEN_DIVIDE,
  _INA_PARSER_EXPR_TOKEN_PLUS,
  _INA_PARSER_EXPR_TOKEN_MINUS,
  _INA_PARSER_EXPR_TOKEN_LPAREN,
  _INA_PARSER_EXPR_TOKEN_RPAREN
} Token;

}
#endif // __INA_PARSER_EXPR2_TOKEN_HH__

