SET(LLVM_CONFIG_EXEC_NAMES "llvm-config"
    "llvm-config-mp-3.1" "llvm-config-3.1"
    "llvm-config-mp-3.0" "llvm-config-3.0"
    "llvm-config-mp-2.9" "llvm-config-2.9")
FIND_PROGRAM(LLVM_CONFIG_EXEC NAMES ${LLVM_CONFIG_EXEC_NAMES})


IF(LLVM_CONFIG_EXEC)
  SET(LLVM_CONFIG_FOUND TRUE)
  EXEC_PROGRAM(perl ARGS ${LLVM_CONFIG_EXEC} "--version"
    OUTPUT_VARIABLE LLVM_VERSION)
ENDIF(LLVM_CONFIG_EXEC)


IF(LLVM_CONFIG_FOUND)
  # get linker flags
  EXEC_PROGRAM(perl ARGS ${LLVM_CONFIG_EXEC} "--ldflags"
    OUTPUT_VARIABLE LLVM_LD_FLAGS)

  # get include dirs:
  EXEC_PROGRAM(perl ARGS ${LLVM_CONFIG_EXEC} "--includedir"
    OUTPUT_VARIABLE LLVM_INCLUDE_DIR)

  # get lib dirs:
  EXEC_PROGRAM(perl ARGS ${LLVM_CONFIG_EXEC} "--libdir"
    OUTPUT_VARIABLE LLVM_LIB_DIR)

  # get libraries:
  EXEC_PROGRAM(perl ARGS ${LLVM_CONFIG_EXEC} "--libs engine interpreter"
    OUTPUT_VARIABLE LLVM_LIBRARY)

  EXEC_PROGRAM(perl ARGS ${LLVM_CONFIG_EXEC} "--cflags"
    OUTPUT_VARIABLE LLVM_C_FLAGS)

  EXEC_PROGRAM(perl ARGS ${LLVM_CONFIG_EXEC} "--cxxflags"
    OUTPUT_VARIABLE LLVM_CXX_FLAGS)

ENDIF(LLVM_CONFIG_FOUND)



INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LLVM DEFAULT_MSG
                                  LLVM_VERSION LLVM_INCLUDE_DIR LLVM_CXX_FLAGS LLVM_LIBRARY LLVM_LD_FLAGS)

SET(LLVM_INCLUDE_DIRS ${LLVM_INCLUDE_DIR})
SET(LLVM_LIBRARIES ${LLVM_LIBRARY} m ffi dl)

IF(WIN32)
    SET(LLVM_LIBRARIES ${LLVM_LIBRARIES} imagehlp psapi)
ENDIF(WIN32)

mark_as_advanced(LLVM_VERSION LLVM_LIBRARY LLVM_INCLUDE_DIR LLVM_CXX_FLAGS LLVM_LD_FLAGS)
